import type { PokemonTypeInfo, PokemonTypeName } from '../types/pokemon';

// 18개 포켓몬 공식 타입 메타데이터 및 테마 색상 (포켓몬 GO 공식/대표 컬러 팔레트)
export const POKEMON_TYPES: Record<PokemonTypeName, PokemonTypeInfo> = {
  normal: {
    id: 'normal',
    nameKo: '노말',
    nameEn: 'Normal',
    color: '#9FA19F',
    textColor: '#FFFFFF',
    bgLight: '#F3F4F6',
    borderColor: '#9FA19F',
  },
  fire: {
    id: 'fire',
    nameKo: '불꽃',
    nameEn: 'Fire',
    color: '#E62829',
    textColor: '#FFFFFF',
    bgLight: '#FEE2E2',
    borderColor: '#EF4444',
  },
  water: {
    id: 'water',
    nameKo: '물',
    nameEn: 'Water',
    color: '#2980EF',
    textColor: '#FFFFFF',
    bgLight: '#DBEAFE',
    borderColor: '#3B82F6',
  },
  grass: {
    id: 'grass',
    nameKo: '풀',
    nameEn: 'Grass',
    color: '#3FA129',
    textColor: '#FFFFFF',
    bgLight: '#DCFCE7',
    borderColor: '#22C55E',
  },
  electric: {
    id: 'electric',
    nameKo: '전기',
    nameEn: 'Electric',
    color: '#FAC000',
    textColor: '#1E293B',
    bgLight: '#FEF9C3',
    borderColor: '#EAB308',
  },
  ice: {
    id: 'ice',
    nameKo: '얼음',
    nameEn: 'Ice',
    color: '#3DCEF3',
    textColor: '#1E293B',
    bgLight: '#E0F2FE',
    borderColor: '#38BDF8',
  },
  fighting: {
    id: 'fighting',
    nameKo: '격투',
    nameEn: 'Fighting',
    color: '#FF8000',
    textColor: '#FFFFFF',
    bgLight: '#FFEDD5',
    borderColor: '#F97316',
  },
  poison: {
    id: 'poison',
    nameKo: '독',
    nameEn: 'Poison',
    color: '#9141CB',
    textColor: '#FFFFFF',
    bgLight: '#F3E8FF',
    borderColor: '#A855F7',
  },
  ground: {
    id: 'ground',
    nameKo: '땅',
    nameEn: 'Ground',
    color: '#915121',
    textColor: '#FFFFFF',
    bgLight: '#FEF3C7',
    borderColor: '#D97706',
  },
  flying: {
    id: 'flying',
    nameKo: '비행',
    nameEn: 'Flying',
    color: '#81B9EF',
    textColor: '#FFFFFF',
    bgLight: '#E0F2FE',
    borderColor: '#60A5FA',
  },
  psychic: {
    id: 'psychic',
    nameKo: '에스퍼',
    nameEn: 'Psychic',
    color: '#EF4179',
    textColor: '#FFFFFF',
    bgLight: '#FCE7F3',
    borderColor: '#EC4899',
  },
  bug: {
    id: 'bug',
    nameKo: '벌레',
    nameEn: 'Bug',
    color: '#91A119',
    textColor: '#FFFFFF',
    bgLight: '#ECFCCB',
    borderColor: '#84CC16',
  },
  rock: {
    id: 'rock',
    nameKo: '바위',
    nameEn: 'Rock',
    color: '#AFA981',
    textColor: '#FFFFFF',
    bgLight: '#F5F5F4',
    borderColor: '#A8A29E',
  },
  ghost: {
    id: 'ghost',
    nameKo: '고스트',
    nameEn: 'Ghost',
    color: '#704170',
    textColor: '#FFFFFF',
    bgLight: '#F3E8FF',
    borderColor: '#7E22CE',
  },
  dragon: {
    id: 'dragon',
    nameKo: '드래곤',
    nameEn: 'Dragon',
    color: '#5060E1',
    textColor: '#FFFFFF',
    bgLight: '#E0E7FF',
    borderColor: '#6366F1',
  },
  dark: {
    id: 'dark',
    nameKo: '악',
    nameEn: 'Dark',
    color: '#50413F',
    textColor: '#FFFFFF',
    bgLight: '#F3F4F6',
    borderColor: '#4B5563',
  },
  steel: {
    id: 'steel',
    nameKo: '강철',
    nameEn: 'Steel',
    color: '#60A1B8',
    textColor: '#FFFFFF',
    bgLight: '#F1F5F9',
    borderColor: '#94A3B8',
  },
  fairy: {
    id: 'fairy',
    nameKo: '페어리',
    nameEn: 'Fairy',
    color: '#EF70EF',
    textColor: '#FFFFFF',
    bgLight: '#FDF2F8',
    borderColor: '#F472B6',
  },
};

export const ALL_TYPE_NAMES: PokemonTypeName[] = [
  'normal',
  'fire',
  'water',
  'grass',
  'electric',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
];

// 포켓몬 GO 상성 계수
export const GO_MULTIPLIER = {
  SUPER_EFFECTIVE: 1.6,
  NEUTRAL: 1.0,
  NOT_VERY_EFFECTIVE: 0.625,
  IMMUNE: 0.390625, // 본가의 0배는 GO에서 0.625^2 = 0.390625 (약 0.39배)
};

// [공격 타입][방어 타입] 배율 매트릭스 (포켓몬 GO 기준)
// 미명시된 조합은 기본 1.0(NEUTRAL)
export const TYPE_EFFECTIVENESS: Record<PokemonTypeName, Partial<Record<PokemonTypeName, number>>> = {
  normal: {
    rock: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ghost: GO_MULTIPLIER.IMMUNE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  fire: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    water: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ice: GO_MULTIPLIER.SUPER_EFFECTIVE,
    bug: GO_MULTIPLIER.SUPER_EFFECTIVE,
    rock: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    dragon: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    steel: GO_MULTIPLIER.SUPER_EFFECTIVE,
  },
  water: {
    fire: GO_MULTIPLIER.SUPER_EFFECTIVE,
    water: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.SUPER_EFFECTIVE,
    rock: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dragon: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  grass: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    water: GO_MULTIPLIER.SUPER_EFFECTIVE,
    grass: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    poison: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.SUPER_EFFECTIVE,
    flying: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    bug: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    rock: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dragon: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  electric: {
    water: GO_MULTIPLIER.SUPER_EFFECTIVE,
    electric: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.IMMUNE,
    flying: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dragon: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  ice: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    water: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ice: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.SUPER_EFFECTIVE,
    flying: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dragon: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  fighting: {
    normal: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ice: GO_MULTIPLIER.SUPER_EFFECTIVE,
    poison: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    flying: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    psychic: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    bug: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    rock: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ghost: GO_MULTIPLIER.IMMUNE,
    dark: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.SUPER_EFFECTIVE,
    fairy: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  poison: {
    grass: GO_MULTIPLIER.SUPER_EFFECTIVE,
    poison: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    rock: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ghost: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    steel: GO_MULTIPLIER.IMMUNE,
    fairy: GO_MULTIPLIER.SUPER_EFFECTIVE,
  },
  ground: {
    fire: GO_MULTIPLIER.SUPER_EFFECTIVE,
    electric: GO_MULTIPLIER.SUPER_EFFECTIVE,
    grass: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    poison: GO_MULTIPLIER.SUPER_EFFECTIVE,
    flying: GO_MULTIPLIER.IMMUNE,
    bug: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    rock: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.SUPER_EFFECTIVE,
  },
  flying: {
    electric: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.SUPER_EFFECTIVE,
    fighting: GO_MULTIPLIER.SUPER_EFFECTIVE,
    bug: GO_MULTIPLIER.SUPER_EFFECTIVE,
    rock: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  psychic: {
    fighting: GO_MULTIPLIER.SUPER_EFFECTIVE,
    poison: GO_MULTIPLIER.SUPER_EFFECTIVE,
    psychic: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    dark: GO_MULTIPLIER.IMMUNE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  bug: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    grass: GO_MULTIPLIER.SUPER_EFFECTIVE,
    fighting: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    poison: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    flying: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    psychic: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ghost: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    dark: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    fairy: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  rock: {
    fire: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ice: GO_MULTIPLIER.SUPER_EFFECTIVE,
    fighting: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ground: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    flying: GO_MULTIPLIER.SUPER_EFFECTIVE,
    bug: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  ghost: {
    normal: GO_MULTIPLIER.IMMUNE,
    psychic: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ghost: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dark: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  dragon: {
    dragon: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    fairy: GO_MULTIPLIER.IMMUNE,
  },
  dark: {
    fighting: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    psychic: GO_MULTIPLIER.SUPER_EFFECTIVE,
    ghost: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dark: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    fairy: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
  steel: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    water: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    electric: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    ice: GO_MULTIPLIER.SUPER_EFFECTIVE,
    rock: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    fairy: GO_MULTIPLIER.SUPER_EFFECTIVE,
  },
  fairy: {
    fire: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    fighting: GO_MULTIPLIER.SUPER_EFFECTIVE,
    poison: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
    dragon: GO_MULTIPLIER.SUPER_EFFECTIVE,
    dark: GO_MULTIPLIER.SUPER_EFFECTIVE,
    steel: GO_MULTIPLIER.NOT_VERY_EFFECTIVE,
  },
};
